#
# Makefile for Vindicator custom drivers
# Author: GrayRavens
#

obj-$(CONFIG_VINDICATOR)		+= vindicator.o
obj-$(CONFIG_VINDICATOR_NOCTURNE)	+= nocturne.o
obj-$(CONFIG_VINDICATOR_EQUILIBRIUM)	+= equilibrium.o
obj-$(CONFIG_VINDICATOR_HERALD)		+= herald.o
obj-$(CONFIG_VINDICATOR_TARGETS)	+= vindicator_targets.o
obj-$(CONFIG_VINDICATOR_KIRYUU)		+= kiryuu.o
obj-$(CONFIG_VINDICATOR_KAGE)		+= kage.o
obj-$(CONFIG_VINDICATOR_TSUKI)		+= tsuki.o
obj-$(CONFIG_VINDICATOR_OTO)		+= oto.o
obj-$(CONFIG_VINDICATOR_SEN)		+= sen.o
obj-$(CONFIG_VINDICATOR_SHUN)		+= shun.o
obj-$(CONFIG_VINDICATOR_KENSHO)		+= kensho.o
