#
# Makefile for Vindicator custom drivers
# Author: GrayRavens
#

obj-$(CONFIG_VINDICATOR)		+= vindicator.o
obj-$(CONFIG_VINDICATOR_NOCTURNE)	+= nocturne.o
obj-$(CONFIG_VINDICATOR_EQUILIBRIUM)	+= equilibrium.o
obj-$(CONFIG_VINDICATOR_HERALD)		+= herald.o
